dist: trusty
sudo: false
group: edge
language: python
python: 3.6
install: pip install .
env:
  - TEST="score dm.edm.json"
  - TEST="score eds.edm.json"
  - TEST="score eds.smatch.json"
  - TEST="score eds.mrp.json"
  - TEST="score dm.sdp.json"
  - TEST="score ucca.ucca.json"
  - TEST="score ucca.smatch.json"
  - TEST="score ucca.mrp.json"
  - TEST="score test.smatch.json"
  - TEST="score coli.smatch.json"
  - TEST="score coli.mrp.json"
  - TEST="sample all"
  - TEST="validate all"
jobs:
  include:
    - os: osx
      language:
      before_install:
        - curl -LO https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
        - bash Miniconda3-latest-MacOSX-x86_64.sh -b -p miniconda
        - export PATH="$PWD/miniconda/bin:$PATH"
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        - conda create -q -n env python=3.6 numpy
        - source activate env
script:
  - make -C data/$TEST TRACE=
